### ISSUE TITLE
Something went wrong during compilation. 

### ISSUE THREAD

**Issue by EvilGodEX** [gesangtome/android_device_nubia_nx627j#2]
Did you add the SELinux tag?

**Comment by gesangtome** [comment]
@EvilGodEX 
Hello, I received your question. If you have a good idea, you can send me the patch via 'pull request' and I will merge it into the trunk after review.

**Comment by EvilGodEX** [comment]
@Flowertome Good idea, maybe I can help you, thanks for your answer!
